# Script 2: BRCA2 ----------------------------------------------------------------

# Study Details -----------------------------------------------------------

# Title: "Assessing the performance of ten pathogenicity prediction algorithms on a dataset of missense brca2 and brca2 mutations."
# Author: Erda Qorri
# Date: 16/05/2022
# Laboratory: HCEMM-BRC Mutagenesis and Carcinogenesis Research Group, Institute of Genetics, Biological Research Centre, Szeged H-6726, Hungary.

# Libraries ----
library(cvms)
library(tidyverse)
library(magrittr)
library(tibble)

# Evaluation Metrics
# PMut ----

PMut_brca2 <-
  read.table("brca2_29-03-2022//PMut_brca2.txt", header = T)

# Converts the PMut object into a tibble
pmut.brca2.tibble <- as_tibble(PMut_brca2)

# Calculates the statistical parameters based on the predictions generated by PMut
pmut_evl_1 <- evaluate(
  pmut.brca2.tibble,
  target_col = "TRUE.",
  prediction_cols = "Predicted",
  type = "binomial",
  positive = "1"
)

View(pmut_evl_1)


# PROVEAN ----

provean_brca2 <-
  read.table("brca2_29-03-2022/PROVEAN_brca2.txt", header = T)

provean_brca2_tibble <- as_tibble(provean_brca2)

provean_evl_brca2 <- evaluate(
  provean_brca2_tibble,
  target_col = "TRUE.",
  prediction_cols = "Predicted",
  type = "binomial"
)

View(provean_evl_brca2)

# SIFT ----

sift_brca2 <-
  read.table("brca2_29-03-2022/SIFT_brca2.txt", header = T)

sift_brca2_tibble <- as_tibble(sift_brca2)

sift_evl_brca2 <- evaluate(
  sift_brca2_tibble,
  target_col = "TRUE.",
  prediction_cols = "Predicted",
  type = "binomial"
)

View(sift_evl_brca2)

# SNPs&GO ----

snpsgo_brca2 <-
  read.table("brca2_29-03-2022/SNPs&GO_brca2.txt", header = T)

snpsgo_brca2_tibble <- as_tibble(snpsgo_brca2)

snpsgo_evl_brca2 <- evaluate(
  snpsgo_brca2_tibble,
  target_col = "TRUE.",
  prediction_cols = "Predicted",
  type = "binomial"
)

View(snpsgo_evl_brca2)

# PhD-SNP ----

phdsnp_brca2 <-
  read.table("brca2_29-03-2022/PhD-SNP_brca2.txt", header = T)

phdsnp_brca2_tibble <- as_tibble(phdsnp_brca2)

phdsnp_evl_brca2 <- evaluate(
  phdsnp_brca2_tibble,
  target_col = "TRUE.",
  prediction_cols = "Predicted",
  type = "binomial"
)

View(phdsnp_evl_brca2)

# PredictSNP ----

predictsnp_brca2 <-
  read.table("brca2_29-03-2022/PredictSNP_brca2.txt", header = T)

predictsnp_brca2_tibble <- as_tibble(predictsnp_brca2)

predictsnp_evl_brca2 <- evaluate(
  predictsnp_brca2_tibble,
  target_col = "TRUE.",
  prediction_cols = "Predicted",
  type = "binomial"
)

View(predictsnp_evl_brca2)

# META-SNP ----

metasnp_brca2 <-
  read.table("brca2_29-03-2022/META-SNP_R_Input.txt", header = T)

metasnp_brca2_tibble <- as_tibble(metasnp_brca2)

metasnp_evl_brca2 <- evaluate(
  metasnp_brca2_tibble,
  target_col = "TRUE.",
  prediction_cols = "Predicted",
  type = "binomial"
)

View(metasnp_evl_brca2)

# PANTHER-PSEP ----

pantherpsep_brca2 <-
  read.table("brca2_29-03-2022/PANTHER-PSEP_brca2.txt", header = T)

pantherpsep_brca2_tibble <- as_tibble(pantherpsep_brca2)

pantherpsep_evl_brca2 <- evaluate(
  pantherpsep_brca2_tibble,
  target_col = "TRUE.",
  prediction_cols = "Predicted",
  type = "binomial"
)

View(pantherpsep_evl_brca2)

# HumDiv ----

humdiv_brca2 <-
  read.table("brca2_29-03-2022/HumDiv_brca2.txt", header = T)

humdiv_brca2_tibble <- as_tibble(humdiv_brca2)

humdiv_evl_brca2 <- evaluate(
  humdiv_brca2_tibble,
  target_col = "TRUE.",
  prediction_cols = "Predicted",
  type = "binomial"
)

View(humdiv_evl_brca2)

# HumVar ----

humvar_brca2 <-
  read.table("brca2_29-03-2022/HumVar_brca2.txt", header = T)

humvar_brca2_tibble <- as_tibble(humvar_brca2)

humvar_evl_brca2 <- evaluate(
  humvar_brca2_tibble,
  target_col = "TRUE.",
  prediction_cols = "Predicted",
  type = "binomial"
)

View(humvar_evl_brca2)