# Script 1 : BRCA1 ----------------------------------------------------------------

# Study Details -----------------------------------------------------------
# Title: "Assessing the performance of ten pathogenicity prediction algorithms on a dataset of missense BRCA1 and BRCA2 mutations."
# Author: Erda Qorri
# Date: 16/05/2022
# Laboratory: HCEMM-BRC Mutagenesis and Carcinogenesis Research Group, Institute of Genetics, Biological Research Centre, Szeged H-6726, Hungary.

# Libraries ----
library(cvms)
library(tidyverse)
library(magrittr)
library(tibble)

# Evaluation Metrics
# PMut ----
PMut_BRCA1 <-
  read.table("BRCA1_29-03-2022//PMut_BRCA1.txt", header = T)

# Converts the PMut object into a tibble
pmut.brca1.tibble <- as_tibble(PMut_BRCA1)

# Calculates the statistical parameters based on the predictions generated by PMut
pmut_evl_1 <- evaluate(
  pmut.brca1.tibble,
  target_col = "TRUE.",
  prediction_cols = "Predicted",
  type = "binomial",
  positive = "1"
)

View(pmut_evl_1)

# PROVEAN ----
provean_brca1 <-
  read.table("BRCA1_29-03-2022/PROVEAN_BRCA1.txt", header = T)

provean_brca1_tibble <- as_tibble(provean_brca1)

provean_evl_brca1 <- evaluate(
  provean_brca1_tibble,
  target_col = "TRUE.",
  prediction_cols = "Predicted",
  type = "binomial"
)

View(provean_evl_brca1)

# SIFT ----
sift_brca1 <-
  read.table("BRCA1_29-03-2022/SIFT_BRCA1.txt", header = T)

sift_brca1_tibble <- as_tibble(sift_brca1)

sift_evl_brca1 <- evaluate(
  sift_brca1_tibble,
  target_col = "TRUE.",
  prediction_cols = "Predicted",
  type = "binomial"
)

View(sift_evl_brca1)
# SNPs&GO ----

snpsgo_brca1 <-
  read.table("BRCA1_29-03-2022/SNPs&GO_BRCA1.txt", header = T)

snpsgo_brca1_tibble <- as_tibble(snpsgo_brca1)

snpsgo_evl_brca1 <- evaluate(
  snpsgo_brca1_tibble,
  target_col = "TRUE.",
  prediction_cols = "Predicted",
  type = "binomial"
)

View(snpsgo_evl_brca1)

# PhD-SNP ----
phdsnp_brca1 <-
  read.table("BRCA1_29-03-2022/PhD-SNP_BRCA1.txt", header = T)

phdsnp_brca1_tibble <- as_tibble(phdsnp_brca1)

phdsnp_evl_brca1 <- evaluate(
  phdsnp_brca1_tibble,
  target_col = "TRUE.",
  prediction_cols = "Predicted",
  type = "binomial"
)

View(phdsnp_evl_brca1)

# PredictSNP ----
predictsnp_brca1 <-
  read.table("BRCA1_29-03-2022/PredictSNP_BRCA1.txt", header = T)

predictsnp_brca1_tibble <- as_tibble(predictsnp_brca1)

predictsnp_evl_brca1 <- evaluate(
  predictsnp_brca1_tibble,
  target_col = "TRUE.",
  prediction_cols = "Predicted",
  type = "binomial"
)

View(predictsnp_evl_brca1)

# META-SNP ----
metasnp_brca1 <-
  read.table("BRCA1_29-03-2022/META-SNP_R_Input.txt", header = T)

metasnp_brca1_tibble <- as_tibble(metasnp_brca1)

metasnp_evl_brca1 <- evaluate(
  metasnp_brca1_tibble,
  target_col = "TRUE.",
  prediction_cols = "Predicted",
  type = "binomial"
)

View(metasnp_evl_brca1)

# PANTHER-PSEP ----
pantherpsep_brca1 <-
  read.table("BRCA1_29-03-2022/PANTHER-PSEP_BRCA1.txt", header = T)

pantherpsep_brca1_tibble <- as_tibble(pantherpsep_brca1)

pantherpsep_evl_brca1 <- evaluate(
  pantherpsep_brca1_tibble,
  target_col = "TRUE.",
  prediction_cols = "Predicted",
  type = "binomial"
)

View(pantherpsep_evl_brca1)

# HumDiv ----
humdiv_brca1 <-
  read.table("BRCA1_29-03-2022/HumDiv_BRCA1.txt", header = T)

humdiv_brca1_tibble <- as_tibble(humdiv_brca1)

humdiv_evl_brca1 <- evaluate(
  humdiv_brca1_tibble,
  target_col = "TRUE.",
  prediction_cols = "Predicted",
  type = "binomial"
)

View(humdiv_evl_brca1)

# HumVar ----
humvar_brca1 <-
  read.table("BRCA1_29-03-2022/HumVar_BRCA1.txt", header = T)

humvar_brca1_tibble <- as_tibble(humvar_brca1)

humvar_evl_brca1 <- evaluate(
  humvar_brca1_tibble,
  target_col = "TRUE.",
  prediction_cols = "Predicted",
  type = "binomial"
)

View(humvar_evl_brca1)
